name: Update GitHub Activity

on:
  schedule:
    - cron: "*/30 * * * *" # Runs every 30 minutes
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update-activity:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run Update GitHub Activity
        uses: ./
        with:
          GITHUB_USERNAME: "thedannicraft"
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          EVENT_LIMIT: 10
          OUTPUT_STYLE: MARKDOWN
          # Avoid the error of starred repos
          IGNORE_EVENTS: '["StarEvent","WatchEvent","ForkEvent"]'
          HIDE_DETAILS_ON_PRIVATE_REPOS: false
          README_PATH: README.md
          COMMIT_MESSAGE: "⚡ Update README.md with latest activity"
          EVENT_EMOJI_MAP: |
            PushEvent: "🚀"
            CreateEvent: "✨"
            DeleteEvent: "🔥"
            IssuesEvent: |
              opened: "🆕"
              closed: "✅"
            PullRequestEvent: |
              opened: "🔀"
          DRY_RUN: false
